sudo: required
services:
  - docker

before_install:
  - docker build -t fango007/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run fango007/react-test npm test -- --coverage

after_success:
  - docker build -t fango007/multi-client ./client
  - docker build -t fango007/multi-nginx ./nginx
  - docker build -t fango007/multi-server ./server
  - docker build -t fango007/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push fango007/multi-client
  - docker push fango007/multi-nginx
  - docker push fango007/multi-server
  - docker push fango007/multi-worker

  # test

deploy:
  provider: elasticbeanstalk
  region: eu-west-3
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-3-575751007176
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY
